# Generated by Django 2.2.6 on 2021-06-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_squashed_0010_auto_20210606_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Напишите текст комментария.', verbose_name='Текст комментария.'),
        ),
    ]
